export const Stations = {
  FRXAB: 'Abbeville',
  FRMLW: 'Aéroport CDG  2 TGV',
  FRXAG: 'Agde',
  FRAGF: 'Agen',
  FRAIS: 'Ailly Sur Somme',
  FRQAI: 'Aime la Plagne',
  FRQXB: 'Aix en Provence',
  FRAIE: 'Aix en Provence TGV',
  FRXAI: 'Aix les Bains le Revard',
  FRALE: 'Albens',
  FRXAV: 'Albertville',
  FRAFJ: 'Albi ville',
  FRXAN: 'Alençon',
  FRALC: 'Allassac',
  FRAMB: 'Ambérieu',
  FRQAM: 'Amiens',
  FREFN: 'Ancenis',
  FRACL: 'Angers St Laud',
  FRANG: 'Angoulême',
  FRNCY: 'Annecy',
  FRQNJ: 'Annemasse',
  FRXAT: 'Antibes',
  FRXAC: 'Arcachon',
  FRART: 'Argentan',
  FRHZA: 'Arles',
  FRQRV: 'Arras',
  FRAUH: 'Auch',
  FRXOY: 'Aulnoye Aymeries',
  FRXUY: 'Auray',
  FRHIQ: 'Aurec',
  FRAUR: 'Aurillac',
  FRASG: 'Auxerre Saint Gervais',
  FRAES: 'Avignon Centre',
  FRIHW: 'Avignon Sud',
  FRAVG: 'Avignon TGV',
  FRXBD: 'Bar le Duc',
  FRHIT: 'Bas-Monistrol',
  FRXBY: 'Bayonne',
  FRXBV: 'Beaune',
  FRBOR: 'Belfort',
  FRTJA: 'Belfort Montbéliard TGV',
  FRXBF: 'Bellegarde',
  FREGC: 'Bergerac',
  FRTJB: 'Besançon Franche-Comté TGV',
  FRABG: 'Besançon Viotte',
  FRXBH: 'Béthune',
  FRBZR: 'Béziers',
  FRBIQ: 'Biarritz',
  FRFAC: 'Biganos - Facture',
  FRXBQ: 'Blois',
  FRHTV: 'Bonneville',
  FRHSL: 'Bons en Chablais',
  FRBOJ: 'Bordeaux St-Jean',
  FRAEB: 'Boulogne Ville',
  FRXBK: 'Bourg en Bresse',
  FRBOU: 'Bourges',
  FRQBM: 'Bourg St Maurice',
  FRBSS: 'Boussens',
  FRBES: 'Brest',
  FRXBC: 'Briançon',
  FRHVV: 'Brignoud',
  FRBVE: 'Brive La Gaillarde',
  FRCFR: 'Caen',
  FRZAO: 'Cahors',
  FRSTH: 'Calais Frethun',
  FRAEA: 'Calais Ville',
  FRAFX: 'Cambrai',
  FRJCA: 'Cannes',
  FRCCF: 'Carcassonne',
  FRCTY: 'Castelnaudary',
  FRHVJ: 'Châbons',
  FRCGY: 'Chagny',
  FRXCR: 'Chalons en Champagne',
  FRXCD: 'Chalon sur Saône',
  FRCMF: 'Chambéry - Challes Les Eaux',
  FREAH: 'Champagne Ardenne TGV',
  FRXCZ: 'Charleville Mézières',
  FRQTJ: 'Chartres',
  FRCHR: 'Châteauroux',
  FRXCY: 'Château Thierry',
  FRXCX: 'Châtellerault',
  FRXCW: 'Chaumont',
  FRACK: 'Cherbourg',
  FRCFE: 'Clermont Ferrand',
  FRHCL: 'Clermont-La Rotonde',
  FRCLI: 'Clisson',
  FRHTZ: 'Cluses',
  FRAEJ: 'Colmar',
  FRGAG: 'Commentry',
  FRXCP: 'Compiègne',
  FRGSH: 'Cosne sur Loire',
  FRCSF: 'Creil',
  FRCKH: 'Croix - Wasquehal',
  FRCCY: 'Culmont - Chalindrey',
  FRCUZ: 'Culoz',
  FRACG: 'Dax',
  FRGTH: 'Decize',
  FRAFD: 'Dieppe',
  FRABA: 'Dijon Ville',
  FRDOL: 'Dol',
  FRACE: 'Dole Ville',
  FRDON: 'Don Sainghin',
  FRXDN: 'Douai',
  FRXDR: 'Dreux',
  FRADI: 'Dunkerque',
  FRECE: 'Echirolles',
  FRXEP: 'Epernay',
  FREPL: 'Epinal',
  FRETA: 'Etaples-le Touquet',
  FRXEB: 'Evian les Bains',
  FREVX: 'Evreux Normandie',
  FRBQT: 'Forbach',
  FRFRA: 'Frasne',
  FRFRO: 'Frouard',
  FRTGO: 'Futuroscope',
  FRGAN: 'Gannat',
  FRGAT: 'Gap',
  FRHVX: 'Goncelin',
  FRFSI: 'Gourdon',
  FRGFR: 'Granville',
  FRGNB: 'Grenoble',
  FRHVS: 'Grenoble Universités Gières',
  FRHTB: 'Grésy sur Aix',
  FRHTO: 'Groisy-Thorens-la-Caille',
  FRXGT: 'Guéret',
  FRGGP: 'Guingamp',
  FRHZK: 'Hazebrouck',
  FRAEF: 'Hendaye',
  FRXHE: 'Hyères',
  FRGMU: 'Joigny',
  FRJSY: 'Juvisy TGV',
  FRJEE: 'La Baule Escoublac',
  FRGSL: 'La Charité',
  FREFZ: 'La Haie Fouassière',
  FRLAM: 'Lamballe',
  FRLEY: 'Lancey',
  FRXLD: 'Landerneau',
  FRHPG: 'Landry',
  FRLAG: 'Langres',
  FRLNZ: 'Lannemezan',
  FRLAI: 'Lannion',
  FRLRH: 'La Rochelle Ville',
  FRISI: 'Laroche Migennes',
  FRLRF: 'La Roche sur Foron',
  FRXRO: 'La Roche sur Yon',
  FRLST: 'La Souterraine',
  FRFCJ: 'La Teste',
  FRACR: 'Laval',
  FRXCC: 'Le Creusot TGV',
  FREGU: 'Le Croisic',
  FRHVK: 'Le Grand Lemps',
  FRAEZ: 'Le Havre',
  FRAET: 'Le Mans',
  FRXLE: 'Lens',
  FREGA: 'Le Pallet',
  FREGS: 'Le Pouliguen',
  FRLPY: 'Le Puy en Velay',
  FRXRS: 'Les Arcs Draguignan',
  FRLAB: 'Les Aubrais Orléans',
  FRLSO: "Les Sables d'Olonne",
  FRHLS: 'Lezoux',
  FRXLR: 'Libourne',
  FRLLE: 'Lille Europe',
  FRADJ: 'Lille Flandres',
  FRAGQ: 'Limoges Bénédictins',
  FRXLX: 'Lisieux',
  FRCQL: 'Longueau',
  FRLWY: 'Longwy',
  FRXLL: 'Lons le Saunier',
  FRLRT: 'Lorient',
  FREAM: 'Lorraine TGV',
  FRLDE: 'Lourdes',
  FRLNE: 'Lunéville',
  FRLUR: 'Lure',
  FRHTF: 'Lyon Jean Macé',
  FRLPD: 'Lyon Part Dieu',
  FRLPE: 'Lyon Perrache',
  FRJDQ: 'Lyon St Exupéry TGV',
  FRHSK: 'Machilly',
  FRMLT: 'Macon Loche TGV',
  FRHGU: 'Macon Ville',
  FRHUB: 'Magland',
  FRMTE: 'Mantes la Jolie',
  FRHTW: 'Marigniers',
  FRXMR: 'Marmande',
  FRMLV: 'Marne la Vallée Chessy',
  FRMSC: 'Marseille St Charles',
  FRFKP: 'Masseret',
  FRDJU: 'Massy TGV',
  FRXME: 'Maubeuge',
  FRXMT: 'Menton',
  FRADE: 'Metz Ville',
  FREAJ: 'Meuse TGV',
  FRMAZ: 'Miramas',
  FRAGR: 'Modane',
  FRABZ: 'Moirans',
  FRXMM: 'Monaco Monte Carlo',
  FRGNX: 'Montargis',
  FRXMW: 'Montauban Ville Bourbon',
  FRGWE: 'Montbard',
  FRXMF: 'Montbéliard',
  FRMCH: 'Montchanin',
  FRXMJ: 'Mont de Marsan',
  FRXMK: 'Montélimar',
  FRMCU: 'Montluçon Ville',
  FRMML: 'Montmélian',
  FRMPL: 'Montpellier St Roch',
  FRGZG: 'Morez',
  FRMXN: 'Morlaix',
  FRMCD: 'Mouchard',
  FRXMU: 'Moulins Sur Allier',
  FRQMU: 'Moutiers Salins Brides-les-Bains',
  FRAEK: 'Mulhouse Ville',
  FRENC: 'Nancy Ville',
  FRNTE: 'Nantes',
  FRXNA: 'Narbonne',
  FRNCH: 'Neufchateau',
  FRNVS: 'Nevers',
  FRNIC: 'Nice Ville',
  FRFNI: 'Nîmes',
  FRNIT: 'Niort',
  FRGXC: 'Nuits Saint-Georges',
  FRHQN: 'Nurieux',
  FROIL: 'Oissel',
  FRXOG: 'Orange',
  FRAFK: 'Orléans',
  FRGFI: 'Orthez',
  FROYO: 'Oyonnax',
  FRPAZ: 'Paris Austerlitz',
  FRPBE: 'Paris Bercy',
  FRPST: 'Paris Est',
  FRPLY: 'Paris Gare de Lyon',
  FRPMO: 'Paris Montparnasse',
  FRPNO: 'Paris Nord',
  FRPSL: 'Paris St Lazare',
  FRAEE: 'Pau',
  FRABF: 'Périgueux',
  FRPGF: 'Perpignan',
  FRHSN: 'Perrignier',
  FRPLT: 'Plouaret-Trégor',
  FRPIS: 'Poitiers',
  FRIFI: 'Poliénas',
  FRPTL: 'Pontarlier',
  FRHVZ: 'Pontcharra sur Bréda Allevard',
  FRPDO: 'Pont de Dore le Chambon',
  FREGR: 'Pornichet',
  FRHTK: 'Pringy',
  FRUIP: 'Quimper',
  FRECO: 'Quimperlé',
  FRCVU: 'Rang du Fliers - Verton - Berck',
  FRHVN: 'Reaumont Saint-Cassien',
  FRXRN: 'Redon',
  FRHUF: 'Reignier',
  FRRHE: 'Reims',
  FRRNT: 'Remiremont',
  FRRNS: 'Rennes',
  FRBDT: 'Rethel',
  FRHMS: 'Retournac',
  FRRIO: 'Riom-Châtel Guyon',
  FRHVM: 'Rives',
  FRRNE: 'Roanne',
  FRRCO: 'Rochefort',
  FRRDZ: 'Rodez',
  FRRSP: 'Rosporden',
  FRADP: 'Roubaix',
  FRURD: 'Rouen Rive Droite',
  FRRYN: 'Royan',
  FRHKO: 'Royat-Chamalières',
  FRFDS: 'Ruffec',
  FRHTE: 'Rumilly',
  FRSAB: 'Sablé',
  FRSZE: 'Saincaize',
  FRSAG: 'Saint-André le Gaz',
  FRHOJ: 'Saint-Avre la Chambre',
  FRSBK: 'Saint-Brieuc',
  FRHEL: 'Saint-Clair les Roches',
  FRXTD: 'Saint-Dié des Vosges',
  FRHVR: 'Saint-Egrève-Saint-Robert',
  FRXST: 'Saintes',
  FRHHD: 'Saint-Etienne Châteaucreux',
  FRSGF: 'Saint-Germain des Fossés',
  FRXGF: 'Saint-Gervais les Bains Le Fayet',
  FRITY: 'Saint-Hilaire-Saint-Nazaire',
  FRXJZ: 'Saint-Jean de Luz Ciboure',
  FRHPN: 'Saint-Jean de Maurienne Arvan',
  FRHSD: 'Saint-Julien en Genevois',
  FREJC: 'Saint-Maixent',
  FRXSB: 'Saint-Malo',
  FRIFG: 'Saint-Marcellin (Isère)',
  FRIWZ: 'Saint-Martin Bellevue',
  FRXVR: 'Saint-Michel Valloire',
  FRSNR: 'Saint-Nazaire',
  FRXSG: 'Saint-Omer',
  FRHTT: 'Saint-Pierre en Faucigny',
  FRSPT: 'Saint-Pol sur Ternoise',
  FRXSJ: 'Saint-Quentin',
  FRXSK: 'Saint-Raphaël Valescure',
  FRSSL: 'Saint-Sulpice Laurière',
  FRXSN: 'Sallanches Combloux Megève',
  FRSBG: 'Sarrebourg',
  FRACN: 'Saumur',
  FRSNE: 'Saverne',
  FRXSW: 'Sedan',
  FRXSQ: 'Sélestat',
  FRXSF: 'Sens',
  FRXSY: 'Sète',
  FRFPH: 'St Gaudens',
  FRXSH: 'St Pierre des Corps',
  FRAEG: 'Strasbourg',
  FREIP: 'Surgères',
  FRXTB: 'Tarbes',
  FRTHP: 'TGV Haute-Picardie',
  FRXTH: 'Thionville',
  FRXTS: 'Thonon les Bains',
  FRTOL: 'Toul',
  FRTLN: 'Toulon',
  FRXYT: 'Toulouse Matabiau',
  FRADM: 'Tourcoing',
  FRHGQ: 'Tournus',
  FRAFW: 'Tours',
  FRTRD: 'Trouville - Deauville',
  FRQYR: 'Troyes',
  FRIFJ: 'Tullins-Fures',
  FRUSS: 'Ussel',
  FRAAW: 'Uzerche',
  FRVDR: 'Val De Reuil',
  FRVAF: 'Valence',
  FRFRK: "Valence d'Agen",
  FRVLA: 'Valence TGV Rhône Alpes Sud',
  FRXVS: 'Valenciennes',
  FRHSB: 'Valleiry',
  FRVNE: 'Vannes',
  FRESL: 'Vendôme Villiers sur Loir',
  FRDQC: 'Vernon',
  FRDHT: 'Versailles Chantiers',
  FRXVO: 'Vesoul',
  FRVHY: 'Vichy',
  FRXVI: 'Vienne',
  FRXVZ: 'Vierzon Ville',
  FRFIY: 'Vigeois',
  FRDUO: 'Villedieu Les Poêles',
  FRFUP: 'Villefranche de Lauragais',
  FRIFH: 'Vinay',
  FRDUX: 'Vire',
  FRHVI: 'Virieu sur Bourbre',
  FRXVT: 'Vitré',
  FRBFO: 'Vitry le François',
  FRHNZ: 'Viviers du Lac',
  FRHVO: 'Voiron',
  FRHVQ: 'Voreppe',
};
